version: "3.5"
services:

  # WebServer
  nginx:
    build: ./nginx/
    container_name: my_nginx
    restart: always
    ports:
      # - 80:80
      - 443:443
    networks:
      - backend
    volumes:
      - wp:/www/wordpress
    depends_on:
      - wordpress

  # Wordpress & PHP
  wordpress:
    build: ./wordpress/
    container_name: my_wordpress
    restart: always
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - wp:/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env

  # DataBase
  mariadb:
    build: ./mariadb/
    container_name: my_mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    env_file:
      - .env

  # Adminer
  adminer:
    build: ./adminer/
    container_name: my_adminer
    restart: always
    ports:
      - "5000:5000"
    networks:
      - backend

# Volumes
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: ./data/DB
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: ./data/WordPress
      o: bind

# Networks
networks:
  backend:
