version: "3.5"
services:

  # WebServer
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - 443:443
    networks:
      - backend
    volumes:
      - wp:/www/wordpress
    depends_on:
      - wordpress

  # Wordpress & PHP
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - wp:/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env

  # DataBase
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    env_file:
      - .env

  # Adminer
  adminer:
    build: ./requirements/adminer/
    container_name: adminer
    restart: always
    ports:
      - "5000:5000"
    networks:
      - backend

# Volumes
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/iel-ferk/Inception/srcs/requirements/data/DB
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/iel-ferk/Inception/srcs/requirements/data/WordPress
      o: bind

# Networks
networks:
  backend:
