version: '3'

services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    # environment:
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_USER: issam
    #   MYSQL_PASSWORD: issam123!
    #   MYSQL_ROOT_PASSWORD: issam123!
    volumes:
      - ./data/db-data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - ./data/www-data:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - ./data/www-data:/var/www/html/wordpress
    ports:
      - 80:80
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env

networks:
  inception:
    driver: bridge